# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlaylistsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'KalturaPlayer/OVP', :path => '../../kaltura-player-ios'
  pod 'KalturaPlayer/OVP', :git => 'https://github.com/kaltura/kaltura-player-ios', :branch => 'FEC-11456'
  
#  pod 'KalturaPlayer/OTT', :path => '../../kaltura-player-ios'
  pod 'KalturaPlayer/OTT', :git => 'https://github.com/kaltura/kaltura-player-ios', :branch => 'FEC-11456'
  
#  pod 'PlayKit', :path => '../../playkit-ios'
  pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios', :branch => 'FEC-11456'
  
#  pod 'PlayKitProviders', :path => '../../playkit-ios-providers'
  pod 'PlayKitProviders', :git => 'https://github.com/kaltura/playkit-ios-providers', :branch => 'FEC-11499'
  
#  pod 'PlayKitKava', :path => '../../playkit-ios-kava'
  
  target 'PlaylistsSampleTests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end

  target 'PlaylistsSampleUITests' do
    # Pods for testing
  end

end
