# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlaylistsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KalturaPlayer/OVP', :path => '../../kaltura-player-ios'
  pod 'KalturaPlayer/OTT', :path => '../../kaltura-player-ios'
  pod 'PlayKit', :path => '../../playkit-ios'
  pod 'PlayKitProviders', :path => '../../playkit-ios-providers'
  
  target 'PlaylistsSampleTests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end

  target 'PlaylistsSampleUITests' do
    # Pods for testing
  end

end
