# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'BasicSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #pod 'KalturaPlayer'
  pod 'KalturaPlayer', :path => '../../kaltura-player-ios'


  ## In case we want to add IMA (Interactive Media Ads)
  #pod 'PlayKit_IMA'
  pod 'PlayKit_IMA', :git => 'https://github.com/kaltura/playkit-ios-ima.git', :branch => 'develop'

  
  ## In case we want to add Youbora
  pod 'PlayKitYoubora'
  

  ## In case we want Offline content (can replace: pod 'KalturaPlayer') 
  #pod 'KalturaPlayer/Offline'
  pod 'KalturaPlayer/Offline', :path => '../../kaltura-player-ios'

  #--- In order to work with the unreleased versions --- Will be removed once released ---

  pod 'DownloadToGo', :path => '../../playkit-ios-dtg'
  pod 'PlayKitUtils', :path => '../../playkit-ios-utils'

end
