# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'BasicSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KalturaPlayer'
#  pod 'KalturaPlayer', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'develop'
#  pod 'KalturaPlayer', :path => '../../kaltura-player-ios'


  ## In case we want to add IMA (Interactive Media Ads)
  pod 'PlayKit_IMA'
#  pod 'PlayKit_IMA', :git => 'https://github.com/kaltura/playkit-ios-ima.git', :branch => 'develop'
#  pod 'PlayKit_IMA', :path => '../../playkit-ios-ima'

  
  ## In case we want to add Youbora
  pod 'PlayKitYoubora'
#  pod 'PlayKitYoubora', :git => 'https://github.com/kaltura/playkit-ios-youbora.git', :branch => 'develop'
#  pod 'PlayKitYoubora', :path => '../../playkit-ios-youbora'
  

  ## In case we want Offline content (can replace: pod 'KalturaPlayer') 
  pod 'KalturaPlayer/Offline'
#  pod 'KalturaPlayer/Offline', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'develop'
#  pod 'KalturaPlayer/Offline', :path => '../../kaltura-player-ios'  

end
