# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Uncomment to use a local copy of KalturaPlayer
KALTURA_PLAYER_LOCAL='../../kaltura-player-ios'

# Uncomment to use a git copy
#KALTURA_PLAYER_GIT='https://github.com/kaltura/kaltura-player-ios.git'

KALTURA_PLAYER_BRANCH=ENV['KP_BRANCH'] || 'develop'

target 'BasicSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  if defined? KALTURA_PLAYER_LOCAL
    pod 'KalturaPlayer', :path => KALTURA_PLAYER_LOCAL
    else
    if defined? KALTURA_PLAYER_GIT
      pod 'KalturaPlayer', :git => KALTURA_PLAYER_GIT, :branch => KALTURA_PLAYER_BRANCH
      else
      pod 'KalturaPlayer'
    end
  end

  # In case we want to add IMA (Interactive Media Ads)
#  pod 'PlayKit_IMA'
pod 'PlayKit_IMA', :git => 'https://github.com/kaltura/playkit-ios-ima.git', :branch => 'develop'
  
  # In case we want to add Youbora
  pod 'PlayKitYoubora'

end
