# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


target 'OTTSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #####################################################################

#  pod 'KalturaPlayer/OTT'

  ### In case we want Offline content (This can replace: pod 'KalturaPlayer/OTT') ###

#  pod 'KalturaPlayer/Offline_OTT'
  pod 'KalturaPlayer/Offline_OTT', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'ForQA_TravisIssue'
#  pod 'KalturaPlayer/Offline_OTT', :path => '../../kaltura-player-ios'

  #####################################################################

 ### In case we want KalturaPlayer UI ###

#  pod 'KalturaPlayer/UI'
  pod 'KalturaPlayer/UI', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'ForQA_TravisIssue'
#  pod 'KalturaPlayer/UI', :path => '../../kaltura-player-ios'

  #####################################################################

  ### In case we want to add IMA (Interactive Media Ads) ###

  pod 'PlayKit_IMA'
#  pod 'PlayKit_IMA', :git => 'https://github.com/kaltura/playkit-ios-ima.git', :branch => 'develop'
#  pod 'PlayKit_IMA', :path => '../../playkit-ios-ima'

  #####################################################################

  ### In case we want to add Youbora ###

#  pod 'PlayKitYoubora'
  pod 'PlayKitYoubora', :git => 'https://github.com/kaltura/playkit-ios-youbora.git', :branch => 'develop'
#  pod 'PlayKitYoubora', :path => '../../playkit-ios-youbora'

  #####################################################################

  ### In case we want to add Google Chrome Cast ###

  pod 'PlayKitGoogleCast'
#  pod 'PlayKitGoogleCast', :git => 'https://github.com/kaltura/playkit-ios-googlecast.git', :branch => 'develop'
#  pod 'PlayKitGoogleCast', :path => '../../playkit-ios-googlecast'
    

### FOR QA

pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios.git', :branch => 'develop'
pod 'PlayKitProviders', :git => 'https://github.com/kaltura/playkit-ios-providers.git', :branch => 'develop'
pod 'PlayKitKava', :git => 'https://github.com/kaltura/playkit-ios-kava.git', :branch => 'develop'
pod 'DownloadToGo', :git => 'https://github.com/kaltura/playkit-ios-dtg.git', :branch => 'develop'
pod 'KalturaNetKit', :git => 'https://github.com/kaltura/netkit-ios.git', :branch => 'develop'

pod 'PlayKitSmartSwitch', :git => 'https://github.com/kaltura/playkit-ios-smartswitch.git', :branch => 'develop'


end
