# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'OVPSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


#  pod 'KalturaPlayer/OVP', '4.0.0.beta.1'
#  pod 'KalturaPlayer/OVP', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'develop'
  pod 'KalturaPlayer/OVP', :path => '../../kaltura-player-ios'


  ## In case we want to add IMA (Interactive Media Ads)
  pod 'PlayKit_IMA'
#  pod 'PlayKit_IMA', :git => 'https://github.com/kaltura/playkit-ios-ima.git', :branch => 'develop'


  ## In case we want to add Youbora
  pod 'PlayKitYoubora'
#  pod 'PlayKitYoubora', :git => 'https://github.com/kaltura/playkit-ios-youbora.git', :branch => 'develop'


=begin
Removing Offline until a fix will be provided by Cocoapods or Realm for the release in Xcode 12.
https://github.com/realm/realm-cocoa/issues/6800

  ## In case we want Offline content (can replace: pod 'KalturaPlayer/OVP')
#  pod 'KalturaPlayer/Offline_OVP'
  pod 'KalturaPlayer/Offline_OVP', :path => '../../kaltura-player-ios'

=end

  #--- In order to work with the unreleased versions --- Will be removed once released ---

pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios.git', :branch => 'develop'
#pod 'PlayKit', :path => '../../playkit-ios'
  
pod 'PlayKitProviders', :git => 'https://github.com/kaltura/playkit-ios-providers.git', :branch => 'FEC-10671'

end
