# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OVPSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


#  pod 'KalturaPlayer/OVP', '4.0.0.beta.2'
  pod 'KalturaPlayer/OVP', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'FEC-10497'
#  pod 'KalturaPlayer/OVP', :path => '../../kaltura-player-ios'


  ## In case we want to add IMA (Interactive Media Ads)
#  pod 'PlayKit_IMA'
  pod 'PlayKit_IMA', :git => 'https://github.com/kaltura/playkit-ios-ima.git', :branch => 'FEC-10431'
#  pod 'PlayKit_IMA', :path => '../../playkit-ios-ima'


  ## In case we want to add Youbora
#  pod 'PlayKitYoubora'
  pod 'PlayKitYoubora', :git => 'https://github.com/kaltura/playkit-ios-youbora.git', :branch => 'FEC-10434'
#  pod 'PlayKitYoubora', :path => '../../playkit-ios-youbora'


  ## In case we want Offline content (can replace: pod 'KalturaPlayer/OVP')
#  pod 'KalturaPlayer/Offline_OVP'
  pod 'KalturaPlayer/Offline_OVP', :git => 'https://github.com/kaltura/kaltura-player-ios.git', :branch => 'FEC-10497'
#  pod 'KalturaPlayer/Offline_OVP', :path => '../../kaltura-player-ios'


  #--- In order to work with the unreleased versions --- Will be removed once released ---

  pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios.git', :branch => 'develop'
#  pod 'PlayKit', :path => '../../playkit-ios'
  
#  pod 'PlayKitProviders', :git => 'https://github.com/kaltura/playkit-ios-providers.git', :branch => 'develop'
#  pod 'PlayKitProviders', :path => '../../playkit-ios-providers'

  pod 'DownloadToGo', :git => 'https://github.com/kaltura/playkit-ios-dtg.git', :branch => 'FEC-10431'
#  pod 'DownloadToGo', :path => '../../playkit-ios-dtg'

end
