platform :ios, '10.0'

target 'PlayKitYouboraSample' do
  use_frameworks!

  pod 'PlayKitYoubora', :path => '../../'

  target 'PlayKitYouboraSampleTests' do
    inherit! :search_paths

    pod 'PlayKitYoubora', :path => '../../'
  end

  target 'PlayKitYouboraSampleUITests' do
    # Pods for testing
  end

end
